### ISSUE TITLE
please add prismarine shard recipe

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/foreshadowing#15]
because i ran out of sanity looking for sea monuments so i can finally upgrade my builder to level 5.

**Comment by kreezxil** [comment]
ti's already added honey.

make prismarine crystals.

then put them in a corail recycler to get shards.

**Comment by kreezxil** [comment]
and yes it doesn't show up in jei, i don't think any of corail's grinding recipes show up in jei
