### ISSUE TITLE
Vanilla Tweaks masks the chiseled stone recipe

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/foreshadowing#16]
vanilla things adds a recipe with which you get stone bricks back by combining two stone brick slabs stacked on each other but that's also the recipe to make chiseled stone bricks which you need for certain minecolony buildings

**Comment by kreezxil** [comment]
make the stone cutter from vanilla. put stone in it, instantly make any variety you want. sadly jei doesn't pick these recipes up either. :(

Thanks for the reports my beautiful player. keep it up.

I'll start a wiki shortly.

**Comment by kreezxil** [comment]
https://youtu.be/FKblRhwiFQ4?t=109

**Comment by kreezxil** [comment]
https://github.com/mezz/JustEnoughItems/issues/1735
