### ISSUE TITLE
Recipe conflict Comforts White Sleeping Bag

### ISSUE THREAD

**Issue by mummabia** [kreezxil/foreshadowing#21]
Hi - I noticed a recipe conflict with Comforts White Sleeping Bag and Ultimate Car Mod Cable Insulator.  Also for Yellow Sleeping Bag.  I noted Green Sleeping Bag recipe conflicts with Green Wool Slabs. Haven't tried other colours.  Thanks.

**Comment by kreezxil** [comment]
thanks for your report, I've filed a report at ultimate car mod, feel free to go add to it. https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/issues/100

Until then I will get a solution in place for today's patch.

**Comment by kreezxil** [comment]
I checked, the problem exists for all the colors of wool

**Comment by kreezxil** [comment]
ok, this is fixed using crafttweaker. I'll close it for now.
