### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by purestone9** [kreezxil/foreshadowing#25]
Emerald armor from Pickle tweaks
Emerald armor from Cyclic

**Comment by kreezxil** [comment]
cyclic failed on the latest forge update and we have too many registered problems. i don't want the pack to wait on this mod to be updated, so the mod is being removed which resolves all the issues associated with it.

**Comment by kreezxil** [comment]
this is very true and it wasn't the only mod that failed. I think we're going to wait thru the weekend before changing out mods. Give other other devs to report on the mods and wait for the mod authors in general to recompile for 31.1.16 or better.

**Comment by kreezxil** [comment]
cyclic version is better, i'll disable the pickle tweaks one instead.
