### ISSUE TITLE
New Mod to replace HWYLA called Look At That

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/foreshadowing#28]
I am waiting on it do some updates https://github.com/Geek202/LookAtThat/issues/2 and then I will replace HWYLA with it.

**Comment by Tom-The-Geek** [comment]
I have pushed that update to CurseForge now :D

**Comment by kreezxil** [comment]
I've actually already added, thanks for the heads up.

**Comment by kreezxil** [comment]
i think i rolled back for something... However, it's in todays version.
