### ISSUE TITLE
[Recipe Conflict] Watering Can

### ISSUE THREAD

**Issue by Warlok333** [kreezxil/foreshadowing#3]
The Pickle Tweaks and Mystical Agriculture Watering Cans both have the same recipe, but the Pickle Tweaks one overrides the other. I would like to be able to craft the Mystical Agriculture Watering Can so that it can then be upgraded to the higher tiers of Watering Can later on. I also can't figure out how to "fill" the Pickle Tweaks can, but that may be user error.

**Comment by kreezxil** [comment]
ok, I'll get this fixed in a few hours.

**Comment by kreezxil** [comment]
I've disabled the watering can from this mod.
