### ISSUE TITLE
insanium essence

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/foreshadowing#31]
force it to use the master infusion crystal (highest tier)

**Comment by kreezxil** [comment]
scratch that make it use a Dark Nether Star Block from Forbidden Arcanus essentially gating those things behind FA.

**Comment by kreezxil** [comment]
so when i tell people to put it here else i'll forget and TouchMe was debating with me about this in Discord. Just because talked about in Discord don't mean I would remember it. I almost forgot this, Not sure I want to trapse back through discord digging out stuff, I can remember the gist of what I was after tho.

**Comment by kreezxil** [comment]
ok, i tweaked the config heavily rebalanced the recipe for the infusion crystal. no more cheap master infusion crystal unless you got one already.

The basic one has 100 uses and requires a nether crystal instead of a cheap diamond. You will have to really think about what you want to do here. Use that one nether star to make a basic infusion crystal or get 4 more to go with it so you can make nether star seeds and essences. This will feel like a reward once you accomplish it in the various stages. This mod is now effectively late game as it should be.

The growth accelerators have been heavily slowed down too, there were previously at 10, now their at 200 for the cooldown.

**Comment by Draconian4466** [comment]
Yeah this will make this mod alot harder considering you cant grow the other teirs
