### ISSUE TITLE
Proposed Config change for Apotheosis

### ISSUE THREAD

**Issue by purestone9** [kreezxil/foreshadowing#36]
I propose the Spawner config file gets changed to the following
https://pastebin.com/SKbwjt0a
it changes the following

Item needed for Ignores Spawn Cap
- Changed from Chorus fruit to Nether Star

The Minimum value of Max Spawn Delay
 - Changed from 0 to 100

Maximum Nearby Entity
 - Changed Max value from 0 to 50

**Comment by kreezxil** [comment]
does this make the mod easier or harder?

**Comment by purestone9** [comment]
I would say harder, but more balanced with what we have in the pack already

**Comment by kreezxil** [comment]
added in todays patch

**Comment by kreezxil** [comment]
added in todays patch
