### ISSUE TITLE
[Please Add] Mekanism + Add Ons

### ISSUE THREAD

**Issue by purestone9** [kreezxil/foreshadowing#57]
More machines and what nots

**Comment by kreezxil** [comment]
mekanism is incompatible with other mods in this pack code wise. it was
causing issues. also you're making the pack too fat, it' has tech, let
those mods mature, it needs magic.

**Comment by kreezxil** [comment]
mekanism is TRUE ALPHA right now. I'll add it as soon as he gets 1.15.2 verison of it beta or release. Closing for now. reopen when that happens.

**Comment by defranke00** [comment]
As of April 23, Mekanism and sub mods have been released in beta

**Comment by kreezxil** [comment]
also, I kind of would rather not, I would like to see the mod authors for the current tech mods in the pack to catch up to the rest of the community and that won't  happen if we don't play their mods and report bugs to them. Already the main mod providing the tech in the pack was made a lot of good changes.

If I add mekanism, that will stop happening.

Furhter we'll see the digiminers on the server hogging the spaces with their giant floating ore piles.
