### ISSUE TITLE
[Please Add] Fast Leaf Decay

### ISSUE THREAD

**Issue by purestone9** [kreezxil/foreshadowing#58]
Fast Leaf Decay

When add, please disable auto sapling replant

**Comment by kreezxil** [comment]
we have a fast leafe decayer, it's the same mod that takes down any tree.

**Comment by kreezxil** [comment]
auto replanting was disabled on the server but not the client, fixed. also you violated my rule of 1 issue per ticket.

leaf breaking functionality restored, in the mod that was providing it, "falling tree".
