### ISSUE TITLE
omega craft magmite ingot recipe appears broken/missing

### ISSUE THREAD

**Issue by T0uchMeSenpai** [kreezxil/foreshadowing#6]
^ title
It's nowhere in the JEI but it was two versions ago.

**Comment by kreezxil** [comment]
For me it wasn't and that was the start of my frustration as you might
recall I was talking about polymers not having recipes listed in the JEI
but in the machine.

Steps to make magmite, first they're called "alloy ingots"

1. crush magmite in an omega craft crusher
2. combine the dust with iron ingots in an omega craft alloy furnace
3. enjoy magmite ingots.

I'm fairly certain this has a lot to do with the odd way we're being forced
to code in 1.15.2

**Comment by kreezxil** [comment]
@T0uchMeSenpai I saw you talking about this on the chat, but did you try it? don't listen to the JEI.

**Comment by kreezxil** [comment]
i think he fixed it, make a new ticket if it is not
