### ISSUE TITLE
Recipe Conflict: Dye Essence

### ISSUE THREAD

**Issue by mummabia** [kreezxil/foreshadowing#62]
Hi,  I've found a few dye recipe conflicts when using Dye Essence.

White dye recipe conflicts with magenta and orange dye.  Each recipe appears on the same centre row in JEI and only crafts white dye regardless of which row you place the dye essence on.

Lime dye recipe conflicts with yellow and light blue dyes.  Each recipe appears on the same centre column in JEI and only crafts white dye regardless of which column you place the dye essence on.

Thanks.

**Comment by kreezxil** [comment]
screen shots would be somewhat helpful, but thanks for the report. We'll fix it soon.

**Comment by kreezxil** [comment]
@mummabia please goto https://github.com/BlakeBr0/MysticalAgriculture/issues/299 and add anything that would help the mod author to identify the issue.

**Comment by kreezxil** [comment]
@mummabia mod author just told me that when I update the "cucumber" library, this problem will be no more. I'll get an update out after 14 hours from this time stamp of this message.

**Comment by kreezxil** [comment]
should be fixed in todays update

**Comment by kreezxil** [comment]
it is most definitely fixed
