### ISSUE TITLE
[Please Add] Disenchanter

### ISSUE THREAD

**Issue by defranke00** [kreezxil/foreshadowing#63]
https://www.curseforge.com/minecraft/mc-mods/disenchantingforge
Successful launch on ssp client.

**Comment by kreezxil** [comment]
and what if it's not successful on the server side of things?

Just need to point out, I can get away with not following the rules for posting please adds and the like, because I know where I am coming from.

I need you peeps to explain to my why it needs to go into the pack.

:)

Have you made it to the blended dimension yet?

**Comment by defranke00** [comment]
If nots not successful on the server side of things, then I would be most interested in seeing what mod had conflict with it, as from what i've seen and heard a multitidue of time, Single player worlds run on a localized server, and would be 'mostly' similar to a normal server. 

Being able to disenchant will allow repurposing the enchanted gear found within dungeons from Dungeon crawl and gear dropped from mobs. As opposed to the WOD disenchanter, this one requires experience to disenchant, which can be adjusted to balance the cost vs normal enchanting, especially when combined with the enchanting cost in the anvil. This can make it so enchanting tables are just as good or better than stealing enchantments from varius gear pieces.

As for the blended dimension, I have never heard of it, neither on google, or with any of the mods in the pack. I've been to the nether (which btw, you've made annoying as hell, so kudos) and I've heard of the gaia and mirror dimensions, though I have not visited them yet.

**Comment by defranke00** [comment]
I see which mod adds blended dimension. Definitely looks, cool, I will have to look into it. Thanks for pointing it out.

**Comment by kreezxil** [comment]
I just made pack actually playable, let's revisit this at a much later time.
