### ISSUE TITLE
Client Crash on random teleport

### ISSUE THREAD

**Issue by defranke00** [kreezxil/foreshadowing#64]
**Describe the bug**

Occasionally, whenever 1 of two commands are executed when on the main server, the client crashes and gives the attached crash report. Given reason: Ticking Entity
**To Reproduce**
1. Log onto server
2. Execute command /mc rtp or /rndtp
3. Repeat until client crashes.

**Versions:**

 - Minecraft: 1.15.2
 - Forge: 31.1.46
 - Mod Pack : 2.9.24
 - Mod Name: N/A
 - Mod Version: N/A

**Logs**

https://gist.github.com/defranke00/8a7c2b9671ae9b0467566dbbf8308cc6

**Comment by kreezxil** [comment]
I recommend going into minecolonies config file and turning off rtp and
going into the Ma Essentials config and turning off random tp there. You
really don't need either on a server as you're being unfair to your
denizens with the intense load caused by these actions.

**Comment by kreezxil** [comment]
just realized your 1wolfsglory
