### ISSUE TITLE
server crash when players places world blender portal blocks

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/foreshadowing#65]
https://github.com/TelepathicGrunt/WorldBlender/issues/7

temporary resolution: remove world blender mod from your server.

**Comment by rwatson1** [comment]
I tried to log in after redownloading the pack and disabling world blender (first try before removing world blender yielded mismatched mod list). I get to encrypting and then the game stops responding, followed by "Took too long to log in." I know of one other person who has the same problem.

Attached is my most recent log file.
[2020-05-07-2.log.gz](https://github.com/kreezxil/foreshadowing/files/4590905/2020-05-07-2.log.gz)

**Comment by kreezxil** [comment]
this is fixed, however I removed it from the pack.
