### ISSUE TITLE
WTBW Quarry Dupe glitch

### ISSUE THREAD

**Issue by Magicalllamasempai** [kreezxil/foreshadowing#7]
It seems to be breaking the Quary block with power inside Gives u the block with power and a new quarry separately. I've only tried breaking it with a diamond paxle. but it works 100% of the time.

**Comment by kreezxil** [comment]
in the future save us some effort and post on the authors site too then bring the link back here for remote tracking. ;) I'll handle this for you. Plus I've also witnessed it.

**Comment by kreezxil** [comment]
https://github.com/WTBW-Mods/WTBW_Machines/issues/5

**Comment by kreezxil** [comment]
I've broken it with other pickaxes.

**Comment by kreezxil** [comment]
fixed
